export const ASYNC_GET_PRODUCTS_LIST = 'ASYNC_GET_PRODUCTS_LIST';
export const ASYNC_GET_PRODUCTS_LIST_SUCCESS = 'ASYNC_GET_PRODUCTS_LIST_SUCCESS';
export const ASYNC_GET_PRODUCTS_LIST_ERROR = 'ASYNC_GET_PRODUCTS_LIST_ERROR';
