type ActionType = string;

export const ADD_PRODUCT_TO_CART: ActionType = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART: ActionType = 'DELETE_PRODUCT_FROM_CART';
export const INCREMENT_PRODUCT_ITEM_QUANTITY: ActionType = 'INCREMENT_PRODUCT_ITEM_QUANTITY';
export const DECREMENT_PRODUCT_ITEM_QUANTITY: ActionType = 'DECREMENT_PRODUCT_ITEM_QUANTITY';
