export const ADD_PRODUCT_TO_CART: string = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART: string = 'DELETE_PRODUCT_FROM_CART';
export const INCREMENT_PRODUCT_ITEM_QUANTITY: string = 'INCREMENT_PRODUCT_ITEM_QUANTITY';
export const DECREMENT_PRODUCT_ITEM_QUANTITY: string = 'DECREMENT_PRODUCT_ITEM_QUANTITY';
