export const BACKEND_REST_URL: string = 'http://localhost:3100';
export const CONTRACTS_BREACH_CODES_SERVICE_URL: string = BACKEND_REST_URL + '/data';
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';

export const REQUEST_PRODUCT_CARDS_LIST = 'REQUEST_PRODUCT_CARDS_LIST';
export const RECEIVE_PRODUCT_CARDS_LIST = 'RECEIVE_PRODUCT_CARDS_LIST';
export const REJECT_PRODUCT_CARDS_LIST = 'REJECT_PRODUCT_CARDS_LIST';