type ActionType = string;

export const ASYNC_GET_PRODUCTS_LIST: ActionType = 'ASYNC_GET_PRODUCTS_LIST';
export const ASYNC_GET_PRODUCTS_LIST_SUCCESS: ActionType = 'ASYNC_GET_PRODUCTS_LIST_SUCCESS';
export const ASYNC_GET_PRODUCTS_LIST_ERROR: ActionType = 'ASYNC_GET_PRODUCTS_LIST_ERROR';
