export const ASYNC_GET_PRODUCTS_LIST: string = 'ASYNC_GET_PRODUCTS_LIST';
export const ASYNC_GET_PRODUCTS_LIST_SUCCESS: string = 'ASYNC_GET_PRODUCTS_LIST_SUCCESS';
export const ASYNC_GET_PRODUCTS_LIST_ERROR: string = 'ASYNC_GET_PRODUCTS_LIST_ERROR';
